/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.api;

import com.logsentinel.ApiException;
import com.logsentinel.model.ActionChainAlertRule;
import com.logsentinel.model.AlertDestination;
import com.logsentinel.model.AlertDestinationRequest;
import com.logsentinel.model.AlertRule;
import com.logsentinel.model.AlertRuleRequest;
import com.logsentinel.model.AlertRuleRun;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AlertsApi
 */
@Ignore
public class AlertsApiTest {

    private final AlertsApi api = new AlertsApi();

    
    /**
     * Creates Action Chain Alert Rule
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createActionChainRuleTest() throws ApiException {
        ActionChainAlertRule alertRule = null;
        ActionChainAlertRule response = api.createActionChainRule(alertRule);

        // TODO: test validations
    }
    
    /**
     * Creates Alert destination. Type is EMAIL or TELEGRAM
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createDestinationTest() throws ApiException {
        AlertDestinationRequest request = null;
        AlertDestination response = api.createDestination(request);

        // TODO: test validations
    }
    
    /**
     * Creates Alert rule. Type is ST_DEV or FIXED. Aggregation type is COUNT, AVG or SUM
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createRuleTest() throws ApiException {
        AlertRuleRequest request = null;
        AlertRule response = api.createRule(request);

        // TODO: test validations
    }
    
    /**
     * Deletes Action chain Alert rule
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteActionChainRuleTest() throws ApiException {
        String id = null;
        api.deleteActionChainRule(id);

        // TODO: test validations
    }
    
    /**
     * Deletes Alert destination
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteDestinationTest() throws ApiException {
        String id = null;
        api.deleteDestination(id);

        // TODO: test validations
    }
    
    /**
     * Deletes Alert rule
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteRuleTest() throws ApiException {
        String id = null;
        api.deleteRule(id);

        // TODO: test validations
    }
    
    /**
     * Gets all Action Chain Alert rules in the organization
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getActionChainAlertRulesTest() throws ApiException {
        List<ActionChainAlertRule> response = api.getActionChainAlertRules();

        // TODO: test validations
    }
    
    /**
     * Gets all Alert destinations in the organization
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAlertDestinationsTest() throws ApiException {
        List<AlertDestination> response = api.getAlertDestinations();

        // TODO: test validations
    }
    
    /**
     * Gets all Alert rule runs in the organization
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAlertRuleRunsTest() throws ApiException {
        List<AlertRuleRun> response = api.getAlertRuleRuns();

        // TODO: test validations
    }
    
    /**
     * Gets all Alert rules in the organization
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAlertRulesTest() throws ApiException {
        List<AlertRule> response = api.getAlertRules();

        // TODO: test validations
    }
    
    /**
     * Updates Action Chain Alert Rule
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateActionChainRuleTest() throws ApiException {
        String id = null;
        ActionChainAlertRule rule = null;
        ActionChainAlertRule response = api.updateActionChainRule(id, rule);

        // TODO: test validations
    }
    
    /**
     * Updates Alert destination. Type cannot be changed
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateDestinationTest() throws ApiException {
        String id = null;
        AlertDestinationRequest request = null;
        AlertDestination response = api.updateDestination(id, request);

        // TODO: test validations
    }
    
    /**
     * Updates Alert rule. Type is ST_DEV or FIXED. Aggregation type is COUNT, AVG or SUM
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateRuleTest() throws ApiException {
        String id = null;
        AlertRuleRequest request = null;
        AlertRule response = api.updateRule(id, request);

        // TODO: test validations
    }
    
}
