/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.api;

import com.logsentinel.ApiException;
import java.util.UUID;
import com.logsentinel.model.UpdateUserRequest;
import com.logsentinel.model.UserDetails;
import com.logsentinel.model.UserRegistrationRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrganizationUsersApi
 */
@Ignore
public class OrganizationUsersApiTest {

    private final OrganizationUsersApi api = new OrganizationUsersApi();

    
    /**
     * Changes user role
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void changeRoleTest() throws ApiException {
        String role = null;
        UUID userId = null;
        UserDetails response = api.changeRole(role, userId);

        // TODO: test validations
    }
    
    /**
     * Creates new user in the organization
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTest() throws ApiException {
        UserRegistrationRequest request = null;
        UserDetails response = api.create(request);

        // TODO: test validations
    }
    
    /**
     * Forgets user profile
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void forgetUserTest() throws ApiException {
        UUID userId = null;
        UserDetails response = api.forgetUser(userId);

        // TODO: test validations
    }
    
    /**
     * Gets user details by email
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserDetailsByEmailTest() throws ApiException {
        String email = null;
        UserDetails response = api.getUserDetailsByEmail(email);

        // TODO: test validations
    }
    
    /**
     * Gets user details by user id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserDetailsByIdTest() throws ApiException {
        UUID userId = null;
        UserDetails response = api.getUserDetailsById(userId);

        // TODO: test validations
    }
    
    /**
     * Updates user profile
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTest() throws ApiException {
        UpdateUserRequest request = null;
        UserDetails response = api.update(request);

        // TODO: test validations
    }
    
}
