/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * ActionChainAlertRule
 */

public class ActionChainAlertRule {
  @JsonProperty("actions")
  private List<String> actions = null;

  @JsonProperty("advancedFilters")
  private List<String> advancedFilters = null;

  @JsonProperty("aggregationPeriod")
  private String aggregationPeriod = null;

  @JsonProperty("alertDestinationIds")
  private List<UUID> alertDestinationIds = null;

  @JsonProperty("applicationId")
  private UUID applicationId = null;

  @JsonProperty("count")
  private List<Integer> count = null;

  @JsonProperty("created")
  private OffsetDateTime created = null;

  @JsonProperty("entityType")
  private String entityType = null;

  @JsonProperty("id")
  private UUID id = null;

  @JsonProperty("initialAction")
  private String initialAction = null;

  @JsonProperty("less")
  private List<Boolean> less = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("organizationId")
  private UUID organizationId = null;

  @JsonProperty("percentage")
  private Integer percentage = null;

  @JsonProperty("searchPeriod")
  private String searchPeriod = null;

  @JsonProperty("sumAction")
  private String sumAction = null;

  @JsonProperty("sumActionTypes")
  private String sumActionTypes = null;

  @JsonProperty("sumTimeFrame")
  private Long sumTimeFrame = null;

  @JsonProperty("sumValuePath")
  private String sumValuePath = null;

  @JsonProperty("timeFrames")
  private List<Long> timeFrames = null;

  @JsonProperty("updated")
  private OffsetDateTime updated = null;

  public ActionChainAlertRule actions(List<String> actions) {
    this.actions = actions;
    return this;
  }

  public ActionChainAlertRule addActionsItem(String actionsItem) {
    if (this.actions == null) {
      this.actions = new ArrayList<>();
    }
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @ApiModelProperty(value = "")
  public List<String> getActions() {
    return actions;
  }

  public void setActions(List<String> actions) {
    this.actions = actions;
  }

  public ActionChainAlertRule advancedFilters(List<String> advancedFilters) {
    this.advancedFilters = advancedFilters;
    return this;
  }

  public ActionChainAlertRule addAdvancedFiltersItem(String advancedFiltersItem) {
    if (this.advancedFilters == null) {
      this.advancedFilters = new ArrayList<>();
    }
    this.advancedFilters.add(advancedFiltersItem);
    return this;
  }

   /**
   * Get advancedFilters
   * @return advancedFilters
  **/
  @ApiModelProperty(value = "")
  public List<String> getAdvancedFilters() {
    return advancedFilters;
  }

  public void setAdvancedFilters(List<String> advancedFilters) {
    this.advancedFilters = advancedFilters;
  }

  public ActionChainAlertRule aggregationPeriod(String aggregationPeriod) {
    this.aggregationPeriod = aggregationPeriod;
    return this;
  }

   /**
   * Get aggregationPeriod
   * @return aggregationPeriod
  **/
  @ApiModelProperty(value = "")
  public String getAggregationPeriod() {
    return aggregationPeriod;
  }

  public void setAggregationPeriod(String aggregationPeriod) {
    this.aggregationPeriod = aggregationPeriod;
  }

  public ActionChainAlertRule alertDestinationIds(List<UUID> alertDestinationIds) {
    this.alertDestinationIds = alertDestinationIds;
    return this;
  }

  public ActionChainAlertRule addAlertDestinationIdsItem(UUID alertDestinationIdsItem) {
    if (this.alertDestinationIds == null) {
      this.alertDestinationIds = new ArrayList<>();
    }
    this.alertDestinationIds.add(alertDestinationIdsItem);
    return this;
  }

   /**
   * Get alertDestinationIds
   * @return alertDestinationIds
  **/
  @ApiModelProperty(value = "")
  public List<UUID> getAlertDestinationIds() {
    return alertDestinationIds;
  }

  public void setAlertDestinationIds(List<UUID> alertDestinationIds) {
    this.alertDestinationIds = alertDestinationIds;
  }

  public ActionChainAlertRule applicationId(UUID applicationId) {
    this.applicationId = applicationId;
    return this;
  }

   /**
   * Get applicationId
   * @return applicationId
  **/
  @ApiModelProperty(value = "")
  public UUID getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(UUID applicationId) {
    this.applicationId = applicationId;
  }

  public ActionChainAlertRule count(List<Integer> count) {
    this.count = count;
    return this;
  }

  public ActionChainAlertRule addCountItem(Integer countItem) {
    if (this.count == null) {
      this.count = new ArrayList<>();
    }
    this.count.add(countItem);
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getCount() {
    return count;
  }

  public void setCount(List<Integer> count) {
    this.count = count;
  }

  public ActionChainAlertRule created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public ActionChainAlertRule entityType(String entityType) {
    this.entityType = entityType;
    return this;
  }

   /**
   * Get entityType
   * @return entityType
  **/
  @ApiModelProperty(value = "")
  public String getEntityType() {
    return entityType;
  }

  public void setEntityType(String entityType) {
    this.entityType = entityType;
  }

  public ActionChainAlertRule id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public ActionChainAlertRule initialAction(String initialAction) {
    this.initialAction = initialAction;
    return this;
  }

   /**
   * Get initialAction
   * @return initialAction
  **/
  @ApiModelProperty(value = "")
  public String getInitialAction() {
    return initialAction;
  }

  public void setInitialAction(String initialAction) {
    this.initialAction = initialAction;
  }

  public ActionChainAlertRule less(List<Boolean> less) {
    this.less = less;
    return this;
  }

  public ActionChainAlertRule addLessItem(Boolean lessItem) {
    if (this.less == null) {
      this.less = new ArrayList<>();
    }
    this.less.add(lessItem);
    return this;
  }

   /**
   * Get less
   * @return less
  **/
  @ApiModelProperty(value = "")
  public List<Boolean> getLess() {
    return less;
  }

  public void setLess(List<Boolean> less) {
    this.less = less;
  }

  public ActionChainAlertRule name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ActionChainAlertRule organizationId(UUID organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Get organizationId
   * @return organizationId
  **/
  @ApiModelProperty(value = "")
  public UUID getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(UUID organizationId) {
    this.organizationId = organizationId;
  }

  public ActionChainAlertRule percentage(Integer percentage) {
    this.percentage = percentage;
    return this;
  }

   /**
   * Get percentage
   * @return percentage
  **/
  @ApiModelProperty(value = "")
  public Integer getPercentage() {
    return percentage;
  }

  public void setPercentage(Integer percentage) {
    this.percentage = percentage;
  }

  public ActionChainAlertRule searchPeriod(String searchPeriod) {
    this.searchPeriod = searchPeriod;
    return this;
  }

   /**
   * Get searchPeriod
   * @return searchPeriod
  **/
  @ApiModelProperty(value = "")
  public String getSearchPeriod() {
    return searchPeriod;
  }

  public void setSearchPeriod(String searchPeriod) {
    this.searchPeriod = searchPeriod;
  }

  public ActionChainAlertRule sumAction(String sumAction) {
    this.sumAction = sumAction;
    return this;
  }

   /**
   * Get sumAction
   * @return sumAction
  **/
  @ApiModelProperty(value = "")
  public String getSumAction() {
    return sumAction;
  }

  public void setSumAction(String sumAction) {
    this.sumAction = sumAction;
  }

  public ActionChainAlertRule sumActionTypes(String sumActionTypes) {
    this.sumActionTypes = sumActionTypes;
    return this;
  }

   /**
   * Get sumActionTypes
   * @return sumActionTypes
  **/
  @ApiModelProperty(value = "")
  public String getSumActionTypes() {
    return sumActionTypes;
  }

  public void setSumActionTypes(String sumActionTypes) {
    this.sumActionTypes = sumActionTypes;
  }

  public ActionChainAlertRule sumTimeFrame(Long sumTimeFrame) {
    this.sumTimeFrame = sumTimeFrame;
    return this;
  }

   /**
   * Get sumTimeFrame
   * @return sumTimeFrame
  **/
  @ApiModelProperty(value = "")
  public Long getSumTimeFrame() {
    return sumTimeFrame;
  }

  public void setSumTimeFrame(Long sumTimeFrame) {
    this.sumTimeFrame = sumTimeFrame;
  }

  public ActionChainAlertRule sumValuePath(String sumValuePath) {
    this.sumValuePath = sumValuePath;
    return this;
  }

   /**
   * Get sumValuePath
   * @return sumValuePath
  **/
  @ApiModelProperty(value = "")
  public String getSumValuePath() {
    return sumValuePath;
  }

  public void setSumValuePath(String sumValuePath) {
    this.sumValuePath = sumValuePath;
  }

  public ActionChainAlertRule timeFrames(List<Long> timeFrames) {
    this.timeFrames = timeFrames;
    return this;
  }

  public ActionChainAlertRule addTimeFramesItem(Long timeFramesItem) {
    if (this.timeFrames == null) {
      this.timeFrames = new ArrayList<>();
    }
    this.timeFrames.add(timeFramesItem);
    return this;
  }

   /**
   * Get timeFrames
   * @return timeFrames
  **/
  @ApiModelProperty(value = "")
  public List<Long> getTimeFrames() {
    return timeFrames;
  }

  public void setTimeFrames(List<Long> timeFrames) {
    this.timeFrames = timeFrames;
  }

  public ActionChainAlertRule updated(OffsetDateTime updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Get updated
   * @return updated
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getUpdated() {
    return updated;
  }

  public void setUpdated(OffsetDateTime updated) {
    this.updated = updated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionChainAlertRule actionChainAlertRule = (ActionChainAlertRule) o;
    return Objects.equals(this.actions, actionChainAlertRule.actions) &&
        Objects.equals(this.advancedFilters, actionChainAlertRule.advancedFilters) &&
        Objects.equals(this.aggregationPeriod, actionChainAlertRule.aggregationPeriod) &&
        Objects.equals(this.alertDestinationIds, actionChainAlertRule.alertDestinationIds) &&
        Objects.equals(this.applicationId, actionChainAlertRule.applicationId) &&
        Objects.equals(this.count, actionChainAlertRule.count) &&
        Objects.equals(this.created, actionChainAlertRule.created) &&
        Objects.equals(this.entityType, actionChainAlertRule.entityType) &&
        Objects.equals(this.id, actionChainAlertRule.id) &&
        Objects.equals(this.initialAction, actionChainAlertRule.initialAction) &&
        Objects.equals(this.less, actionChainAlertRule.less) &&
        Objects.equals(this.name, actionChainAlertRule.name) &&
        Objects.equals(this.organizationId, actionChainAlertRule.organizationId) &&
        Objects.equals(this.percentage, actionChainAlertRule.percentage) &&
        Objects.equals(this.searchPeriod, actionChainAlertRule.searchPeriod) &&
        Objects.equals(this.sumAction, actionChainAlertRule.sumAction) &&
        Objects.equals(this.sumActionTypes, actionChainAlertRule.sumActionTypes) &&
        Objects.equals(this.sumTimeFrame, actionChainAlertRule.sumTimeFrame) &&
        Objects.equals(this.sumValuePath, actionChainAlertRule.sumValuePath) &&
        Objects.equals(this.timeFrames, actionChainAlertRule.timeFrames) &&
        Objects.equals(this.updated, actionChainAlertRule.updated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actions, advancedFilters, aggregationPeriod, alertDestinationIds, applicationId, count, created, entityType, id, initialAction, less, name, organizationId, percentage, searchPeriod, sumAction, sumActionTypes, sumTimeFrame, sumValuePath, timeFrames, updated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionChainAlertRule {\n");
    
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    advancedFilters: ").append(toIndentedString(advancedFilters)).append("\n");
    sb.append("    aggregationPeriod: ").append(toIndentedString(aggregationPeriod)).append("\n");
    sb.append("    alertDestinationIds: ").append(toIndentedString(alertDestinationIds)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    entityType: ").append(toIndentedString(entityType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    initialAction: ").append(toIndentedString(initialAction)).append("\n");
    sb.append("    less: ").append(toIndentedString(less)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
    sb.append("    searchPeriod: ").append(toIndentedString(searchPeriod)).append("\n");
    sb.append("    sumAction: ").append(toIndentedString(sumAction)).append("\n");
    sb.append("    sumActionTypes: ").append(toIndentedString(sumActionTypes)).append("\n");
    sb.append("    sumTimeFrame: ").append(toIndentedString(sumTimeFrame)).append("\n");
    sb.append("    sumValuePath: ").append(toIndentedString(sumValuePath)).append("\n");
    sb.append("    timeFrames: ").append(toIndentedString(timeFrames)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

