/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ActorData
 */

public class ActorData {
  @JsonProperty("actorDisplayName")
  private String actorDisplayName = null;

  @JsonProperty("actorId")
  private String actorId = null;

  @JsonProperty("actorRoles")
  private List<String> actorRoles = null;

  @JsonProperty("department")
  private String department = null;

  public ActorData actorDisplayName(String actorDisplayName) {
    this.actorDisplayName = actorDisplayName;
    return this;
  }

   /**
   * Get actorDisplayName
   * @return actorDisplayName
  **/
  @ApiModelProperty(value = "")
  public String getActorDisplayName() {
    return actorDisplayName;
  }

  public void setActorDisplayName(String actorDisplayName) {
    this.actorDisplayName = actorDisplayName;
  }

  public ActorData actorId(String actorId) {
    this.actorId = actorId;
    return this;
  }

   /**
   * Get actorId
   * @return actorId
  **/
  @ApiModelProperty(value = "")
  public String getActorId() {
    return actorId;
  }

  public void setActorId(String actorId) {
    this.actorId = actorId;
  }

  public ActorData actorRoles(List<String> actorRoles) {
    this.actorRoles = actorRoles;
    return this;
  }

  public ActorData addActorRolesItem(String actorRolesItem) {
    if (this.actorRoles == null) {
      this.actorRoles = new ArrayList<>();
    }
    this.actorRoles.add(actorRolesItem);
    return this;
  }

   /**
   * Get actorRoles
   * @return actorRoles
  **/
  @ApiModelProperty(value = "")
  public List<String> getActorRoles() {
    return actorRoles;
  }

  public void setActorRoles(List<String> actorRoles) {
    this.actorRoles = actorRoles;
  }

  public ActorData department(String department) {
    this.department = department;
    return this;
  }

   /**
   * Get department
   * @return department
  **/
  @ApiModelProperty(value = "")
  public String getDepartment() {
    return department;
  }

  public void setDepartment(String department) {
    this.department = department;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActorData actorData = (ActorData) o;
    return Objects.equals(this.actorDisplayName, actorData.actorDisplayName) &&
        Objects.equals(this.actorId, actorData.actorId) &&
        Objects.equals(this.actorRoles, actorData.actorRoles) &&
        Objects.equals(this.department, actorData.department);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actorDisplayName, actorId, actorRoles, department);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActorData {\n");
    
    sb.append("    actorDisplayName: ").append(toIndentedString(actorDisplayName)).append("\n");
    sb.append("    actorId: ").append(toIndentedString(actorId)).append("\n");
    sb.append("    actorRoles: ").append(toIndentedString(actorRoles)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

