/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * AlertDestination
 */

public class AlertDestination {
  @JsonProperty("code")
  private String code = null;

  @JsonProperty("created")
  private OffsetDateTime created = null;

  @JsonProperty("customHeaders")
  private List<String> customHeaders = null;

  @JsonProperty("id")
  private UUID id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("organizationId")
  private UUID organizationId = null;

  @JsonProperty("recipients")
  private List<String> recipients = null;

  @JsonProperty("recipientsNames")
  private List<String> recipientsNames = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    EMAIL("EMAIL"),
    
    TELEGRAM("TELEGRAM"),
    
    URL("URL");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("updated")
  private OffsetDateTime updated = null;

  public AlertDestination code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(value = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public AlertDestination created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public AlertDestination customHeaders(List<String> customHeaders) {
    this.customHeaders = customHeaders;
    return this;
  }

  public AlertDestination addCustomHeadersItem(String customHeadersItem) {
    if (this.customHeaders == null) {
      this.customHeaders = new ArrayList<>();
    }
    this.customHeaders.add(customHeadersItem);
    return this;
  }

   /**
   * Get customHeaders
   * @return customHeaders
  **/
  @ApiModelProperty(value = "")
  public List<String> getCustomHeaders() {
    return customHeaders;
  }

  public void setCustomHeaders(List<String> customHeaders) {
    this.customHeaders = customHeaders;
  }

  public AlertDestination id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public AlertDestination name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AlertDestination organizationId(UUID organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * Get organizationId
   * @return organizationId
  **/
  @ApiModelProperty(value = "")
  public UUID getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(UUID organizationId) {
    this.organizationId = organizationId;
  }

  public AlertDestination recipients(List<String> recipients) {
    this.recipients = recipients;
    return this;
  }

  public AlertDestination addRecipientsItem(String recipientsItem) {
    if (this.recipients == null) {
      this.recipients = new ArrayList<>();
    }
    this.recipients.add(recipientsItem);
    return this;
  }

   /**
   * Get recipients
   * @return recipients
  **/
  @ApiModelProperty(value = "")
  public List<String> getRecipients() {
    return recipients;
  }

  public void setRecipients(List<String> recipients) {
    this.recipients = recipients;
  }

  public AlertDestination recipientsNames(List<String> recipientsNames) {
    this.recipientsNames = recipientsNames;
    return this;
  }

  public AlertDestination addRecipientsNamesItem(String recipientsNamesItem) {
    if (this.recipientsNames == null) {
      this.recipientsNames = new ArrayList<>();
    }
    this.recipientsNames.add(recipientsNamesItem);
    return this;
  }

   /**
   * Get recipientsNames
   * @return recipientsNames
  **/
  @ApiModelProperty(value = "")
  public List<String> getRecipientsNames() {
    return recipientsNames;
  }

  public void setRecipientsNames(List<String> recipientsNames) {
    this.recipientsNames = recipientsNames;
  }

  public AlertDestination type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public AlertDestination updated(OffsetDateTime updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Get updated
   * @return updated
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getUpdated() {
    return updated;
  }

  public void setUpdated(OffsetDateTime updated) {
    this.updated = updated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlertDestination alertDestination = (AlertDestination) o;
    return Objects.equals(this.code, alertDestination.code) &&
        Objects.equals(this.created, alertDestination.created) &&
        Objects.equals(this.customHeaders, alertDestination.customHeaders) &&
        Objects.equals(this.id, alertDestination.id) &&
        Objects.equals(this.name, alertDestination.name) &&
        Objects.equals(this.organizationId, alertDestination.organizationId) &&
        Objects.equals(this.recipients, alertDestination.recipients) &&
        Objects.equals(this.recipientsNames, alertDestination.recipientsNames) &&
        Objects.equals(this.type, alertDestination.type) &&
        Objects.equals(this.updated, alertDestination.updated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, created, customHeaders, id, name, organizationId, recipients, recipientsNames, type, updated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlertDestination {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    customHeaders: ").append(toIndentedString(customHeaders)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    recipients: ").append(toIndentedString(recipients)).append("\n");
    sb.append("    recipientsNames: ").append(toIndentedString(recipientsNames)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

