/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * AuditLogEntry
 */

public class AuditLogEntry {
  @JsonProperty("action")
  private String action = null;

  @JsonProperty("actorDisplayName")
  private String actorDisplayName = null;

  @JsonProperty("actorId")
  private String actorId = null;

  @JsonProperty("actorRoles")
  private List<String> actorRoles = null;

  @JsonProperty("additionalParams")
  private Map<String, String> additionalParams = null;

  @JsonProperty("applicationId")
  private UUID applicationId = null;

  @JsonProperty("details")
  private String details = null;

  @JsonProperty("encryptedKeywordsList")
  private List<String> encryptedKeywordsList = null;

  @JsonProperty("entityId")
  private String entityId = null;

  @JsonProperty("entityType")
  private String entityType = null;

  @JsonProperty("entryType")
  private String entryType = null;

  @JsonProperty("hash")
  private String hash = null;

  @JsonProperty("hashVersion")
  private Integer hashVersion = null;

  @JsonProperty("id")
  private UUID id = null;

  @JsonProperty("insideWorkingHours")
  private Boolean insideWorkingHours = null;

  @JsonProperty("ipAddress")
  private String ipAddress = null;

  /**
   * Gets or Sets logLevel
   */
  public enum LogLevelEnum {
    TRACE("TRACE"),
    
    DEBUG("DEBUG"),
    
    INFO("INFO"),
    
    WARN("WARN"),
    
    ERROR("ERROR"),
    
    CRITICAL("CRITICAL"),
    
    FATAL("FATAL");

    private String value;

    LogLevelEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LogLevelEnum fromValue(String text) {
      for (LogLevelEnum b : LogLevelEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("logLevel")
  private LogLevelEnum logLevel = null;

  @JsonProperty("numericParams")
  private Map<String, Double> numericParams = null;

  @JsonProperty("previousEntryId")
  private UUID previousEntryId = null;

  @JsonProperty("standaloneHash")
  private String standaloneHash = null;

  @JsonProperty("timestamp")
  private Long timestamp = null;

  @JsonProperty("timestampGroupHash")
  private String timestampGroupHash = null;

  @JsonProperty("timestampGroupSize")
  private Integer timestampGroupSize = null;

  @JsonProperty("timestampTime")
  private OffsetDateTime timestampTime = null;

  @JsonProperty("timestampTokenId")
  private UUID timestampTokenId = null;

  public AuditLogEntry action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @ApiModelProperty(value = "")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public AuditLogEntry actorDisplayName(String actorDisplayName) {
    this.actorDisplayName = actorDisplayName;
    return this;
  }

   /**
   * Get actorDisplayName
   * @return actorDisplayName
  **/
  @ApiModelProperty(value = "")
  public String getActorDisplayName() {
    return actorDisplayName;
  }

  public void setActorDisplayName(String actorDisplayName) {
    this.actorDisplayName = actorDisplayName;
  }

  public AuditLogEntry actorId(String actorId) {
    this.actorId = actorId;
    return this;
  }

   /**
   * Get actorId
   * @return actorId
  **/
  @ApiModelProperty(value = "")
  public String getActorId() {
    return actorId;
  }

  public void setActorId(String actorId) {
    this.actorId = actorId;
  }

  public AuditLogEntry actorRoles(List<String> actorRoles) {
    this.actorRoles = actorRoles;
    return this;
  }

  public AuditLogEntry addActorRolesItem(String actorRolesItem) {
    if (this.actorRoles == null) {
      this.actorRoles = new ArrayList<>();
    }
    this.actorRoles.add(actorRolesItem);
    return this;
  }

   /**
   * Get actorRoles
   * @return actorRoles
  **/
  @ApiModelProperty(value = "")
  public List<String> getActorRoles() {
    return actorRoles;
  }

  public void setActorRoles(List<String> actorRoles) {
    this.actorRoles = actorRoles;
  }

  public AuditLogEntry additionalParams(Map<String, String> additionalParams) {
    this.additionalParams = additionalParams;
    return this;
  }

  public AuditLogEntry putAdditionalParamsItem(String key, String additionalParamsItem) {
    if (this.additionalParams == null) {
      this.additionalParams = new HashMap<>();
    }
    this.additionalParams.put(key, additionalParamsItem);
    return this;
  }

   /**
   * Get additionalParams
   * @return additionalParams
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getAdditionalParams() {
    return additionalParams;
  }

  public void setAdditionalParams(Map<String, String> additionalParams) {
    this.additionalParams = additionalParams;
  }

  public AuditLogEntry applicationId(UUID applicationId) {
    this.applicationId = applicationId;
    return this;
  }

   /**
   * Get applicationId
   * @return applicationId
  **/
  @ApiModelProperty(value = "")
  public UUID getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(UUID applicationId) {
    this.applicationId = applicationId;
  }

  public AuditLogEntry details(String details) {
    this.details = details;
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @ApiModelProperty(value = "")
  public String getDetails() {
    return details;
  }

  public void setDetails(String details) {
    this.details = details;
  }

  public AuditLogEntry encryptedKeywordsList(List<String> encryptedKeywordsList) {
    this.encryptedKeywordsList = encryptedKeywordsList;
    return this;
  }

  public AuditLogEntry addEncryptedKeywordsListItem(String encryptedKeywordsListItem) {
    if (this.encryptedKeywordsList == null) {
      this.encryptedKeywordsList = new ArrayList<>();
    }
    this.encryptedKeywordsList.add(encryptedKeywordsListItem);
    return this;
  }

   /**
   * Get encryptedKeywordsList
   * @return encryptedKeywordsList
  **/
  @ApiModelProperty(value = "")
  public List<String> getEncryptedKeywordsList() {
    return encryptedKeywordsList;
  }

  public void setEncryptedKeywordsList(List<String> encryptedKeywordsList) {
    this.encryptedKeywordsList = encryptedKeywordsList;
  }

  public AuditLogEntry entityId(String entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * Get entityId
   * @return entityId
  **/
  @ApiModelProperty(value = "")
  public String getEntityId() {
    return entityId;
  }

  public void setEntityId(String entityId) {
    this.entityId = entityId;
  }

  public AuditLogEntry entityType(String entityType) {
    this.entityType = entityType;
    return this;
  }

   /**
   * Get entityType
   * @return entityType
  **/
  @ApiModelProperty(value = "")
  public String getEntityType() {
    return entityType;
  }

  public void setEntityType(String entityType) {
    this.entityType = entityType;
  }

  public AuditLogEntry entryType(String entryType) {
    this.entryType = entryType;
    return this;
  }

   /**
   * Get entryType
   * @return entryType
  **/
  @ApiModelProperty(value = "")
  public String getEntryType() {
    return entryType;
  }

  public void setEntryType(String entryType) {
    this.entryType = entryType;
  }

  public AuditLogEntry hash(String hash) {
    this.hash = hash;
    return this;
  }

   /**
   * Get hash
   * @return hash
  **/
  @ApiModelProperty(value = "")
  public String getHash() {
    return hash;
  }

  public void setHash(String hash) {
    this.hash = hash;
  }

  public AuditLogEntry hashVersion(Integer hashVersion) {
    this.hashVersion = hashVersion;
    return this;
  }

   /**
   * Get hashVersion
   * @return hashVersion
  **/
  @ApiModelProperty(value = "")
  public Integer getHashVersion() {
    return hashVersion;
  }

  public void setHashVersion(Integer hashVersion) {
    this.hashVersion = hashVersion;
  }

  public AuditLogEntry id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public AuditLogEntry insideWorkingHours(Boolean insideWorkingHours) {
    this.insideWorkingHours = insideWorkingHours;
    return this;
  }

   /**
   * Get insideWorkingHours
   * @return insideWorkingHours
  **/
  @ApiModelProperty(value = "")
  public Boolean isInsideWorkingHours() {
    return insideWorkingHours;
  }

  public void setInsideWorkingHours(Boolean insideWorkingHours) {
    this.insideWorkingHours = insideWorkingHours;
  }

  public AuditLogEntry ipAddress(String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

   /**
   * Get ipAddress
   * @return ipAddress
  **/
  @ApiModelProperty(value = "")
  public String getIpAddress() {
    return ipAddress;
  }

  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }

  public AuditLogEntry logLevel(LogLevelEnum logLevel) {
    this.logLevel = logLevel;
    return this;
  }

   /**
   * Get logLevel
   * @return logLevel
  **/
  @ApiModelProperty(value = "")
  public LogLevelEnum getLogLevel() {
    return logLevel;
  }

  public void setLogLevel(LogLevelEnum logLevel) {
    this.logLevel = logLevel;
  }

  public AuditLogEntry numericParams(Map<String, Double> numericParams) {
    this.numericParams = numericParams;
    return this;
  }

  public AuditLogEntry putNumericParamsItem(String key, Double numericParamsItem) {
    if (this.numericParams == null) {
      this.numericParams = new HashMap<>();
    }
    this.numericParams.put(key, numericParamsItem);
    return this;
  }

   /**
   * Get numericParams
   * @return numericParams
  **/
  @ApiModelProperty(value = "")
  public Map<String, Double> getNumericParams() {
    return numericParams;
  }

  public void setNumericParams(Map<String, Double> numericParams) {
    this.numericParams = numericParams;
  }

  public AuditLogEntry previousEntryId(UUID previousEntryId) {
    this.previousEntryId = previousEntryId;
    return this;
  }

   /**
   * Get previousEntryId
   * @return previousEntryId
  **/
  @ApiModelProperty(value = "")
  public UUID getPreviousEntryId() {
    return previousEntryId;
  }

  public void setPreviousEntryId(UUID previousEntryId) {
    this.previousEntryId = previousEntryId;
  }

  public AuditLogEntry standaloneHash(String standaloneHash) {
    this.standaloneHash = standaloneHash;
    return this;
  }

   /**
   * Get standaloneHash
   * @return standaloneHash
  **/
  @ApiModelProperty(value = "")
  public String getStandaloneHash() {
    return standaloneHash;
  }

  public void setStandaloneHash(String standaloneHash) {
    this.standaloneHash = standaloneHash;
  }

  public AuditLogEntry timestamp(Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public Long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }

  public AuditLogEntry timestampGroupHash(String timestampGroupHash) {
    this.timestampGroupHash = timestampGroupHash;
    return this;
  }

   /**
   * Get timestampGroupHash
   * @return timestampGroupHash
  **/
  @ApiModelProperty(value = "")
  public String getTimestampGroupHash() {
    return timestampGroupHash;
  }

  public void setTimestampGroupHash(String timestampGroupHash) {
    this.timestampGroupHash = timestampGroupHash;
  }

  public AuditLogEntry timestampGroupSize(Integer timestampGroupSize) {
    this.timestampGroupSize = timestampGroupSize;
    return this;
  }

   /**
   * Get timestampGroupSize
   * @return timestampGroupSize
  **/
  @ApiModelProperty(value = "")
  public Integer getTimestampGroupSize() {
    return timestampGroupSize;
  }

  public void setTimestampGroupSize(Integer timestampGroupSize) {
    this.timestampGroupSize = timestampGroupSize;
  }

  public AuditLogEntry timestampTime(OffsetDateTime timestampTime) {
    this.timestampTime = timestampTime;
    return this;
  }

   /**
   * Get timestampTime
   * @return timestampTime
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getTimestampTime() {
    return timestampTime;
  }

  public void setTimestampTime(OffsetDateTime timestampTime) {
    this.timestampTime = timestampTime;
  }

  public AuditLogEntry timestampTokenId(UUID timestampTokenId) {
    this.timestampTokenId = timestampTokenId;
    return this;
  }

   /**
   * Get timestampTokenId
   * @return timestampTokenId
  **/
  @ApiModelProperty(value = "")
  public UUID getTimestampTokenId() {
    return timestampTokenId;
  }

  public void setTimestampTokenId(UUID timestampTokenId) {
    this.timestampTokenId = timestampTokenId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditLogEntry auditLogEntry = (AuditLogEntry) o;
    return Objects.equals(this.action, auditLogEntry.action) &&
        Objects.equals(this.actorDisplayName, auditLogEntry.actorDisplayName) &&
        Objects.equals(this.actorId, auditLogEntry.actorId) &&
        Objects.equals(this.actorRoles, auditLogEntry.actorRoles) &&
        Objects.equals(this.additionalParams, auditLogEntry.additionalParams) &&
        Objects.equals(this.applicationId, auditLogEntry.applicationId) &&
        Objects.equals(this.details, auditLogEntry.details) &&
        Objects.equals(this.encryptedKeywordsList, auditLogEntry.encryptedKeywordsList) &&
        Objects.equals(this.entityId, auditLogEntry.entityId) &&
        Objects.equals(this.entityType, auditLogEntry.entityType) &&
        Objects.equals(this.entryType, auditLogEntry.entryType) &&
        Objects.equals(this.hash, auditLogEntry.hash) &&
        Objects.equals(this.hashVersion, auditLogEntry.hashVersion) &&
        Objects.equals(this.id, auditLogEntry.id) &&
        Objects.equals(this.insideWorkingHours, auditLogEntry.insideWorkingHours) &&
        Objects.equals(this.ipAddress, auditLogEntry.ipAddress) &&
        Objects.equals(this.logLevel, auditLogEntry.logLevel) &&
        Objects.equals(this.numericParams, auditLogEntry.numericParams) &&
        Objects.equals(this.previousEntryId, auditLogEntry.previousEntryId) &&
        Objects.equals(this.standaloneHash, auditLogEntry.standaloneHash) &&
        Objects.equals(this.timestamp, auditLogEntry.timestamp) &&
        Objects.equals(this.timestampGroupHash, auditLogEntry.timestampGroupHash) &&
        Objects.equals(this.timestampGroupSize, auditLogEntry.timestampGroupSize) &&
        Objects.equals(this.timestampTime, auditLogEntry.timestampTime) &&
        Objects.equals(this.timestampTokenId, auditLogEntry.timestampTokenId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, actorDisplayName, actorId, actorRoles, additionalParams, applicationId, details, encryptedKeywordsList, entityId, entityType, entryType, hash, hashVersion, id, insideWorkingHours, ipAddress, logLevel, numericParams, previousEntryId, standaloneHash, timestamp, timestampGroupHash, timestampGroupSize, timestampTime, timestampTokenId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditLogEntry {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    actorDisplayName: ").append(toIndentedString(actorDisplayName)).append("\n");
    sb.append("    actorId: ").append(toIndentedString(actorId)).append("\n");
    sb.append("    actorRoles: ").append(toIndentedString(actorRoles)).append("\n");
    sb.append("    additionalParams: ").append(toIndentedString(additionalParams)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    encryptedKeywordsList: ").append(toIndentedString(encryptedKeywordsList)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    entityType: ").append(toIndentedString(entityType)).append("\n");
    sb.append("    entryType: ").append(toIndentedString(entryType)).append("\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    hashVersion: ").append(toIndentedString(hashVersion)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    insideWorkingHours: ").append(toIndentedString(insideWorkingHours)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    logLevel: ").append(toIndentedString(logLevel)).append("\n");
    sb.append("    numericParams: ").append(toIndentedString(numericParams)).append("\n");
    sb.append("    previousEntryId: ").append(toIndentedString(previousEntryId)).append("\n");
    sb.append("    standaloneHash: ").append(toIndentedString(standaloneHash)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    timestampGroupHash: ").append(toIndentedString(timestampGroupHash)).append("\n");
    sb.append("    timestampGroupSize: ").append(toIndentedString(timestampGroupSize)).append("\n");
    sb.append("    timestampTime: ").append(toIndentedString(timestampTime)).append("\n");
    sb.append("    timestampTokenId: ").append(toIndentedString(timestampTokenId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

