/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.logsentinel.model.ActionData;
import com.logsentinel.model.ActorData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * BatchLogRequestEntry
 */

public class BatchLogRequestEntry {
  @JsonProperty("actionData")
  private ActionData actionData = null;

  @JsonProperty("actorData")
  private ActorData actorData = null;

  @JsonProperty("additionalParams")
  private Map<String, String> additionalParams = null;

  @JsonProperty("binaryContent")
  private Boolean binaryContent = null;

  @JsonProperty("encryptedKeywordsList")
  private List<String> encryptedKeywordsList = null;

  @JsonProperty("signature")
  private String signature = null;

  public BatchLogRequestEntry actionData(ActionData actionData) {
    this.actionData = actionData;
    return this;
  }

   /**
   * Get actionData
   * @return actionData
  **/
  @ApiModelProperty(value = "")
  public ActionData getActionData() {
    return actionData;
  }

  public void setActionData(ActionData actionData) {
    this.actionData = actionData;
  }

  public BatchLogRequestEntry actorData(ActorData actorData) {
    this.actorData = actorData;
    return this;
  }

   /**
   * Get actorData
   * @return actorData
  **/
  @ApiModelProperty(value = "")
  public ActorData getActorData() {
    return actorData;
  }

  public void setActorData(ActorData actorData) {
    this.actorData = actorData;
  }

  public BatchLogRequestEntry additionalParams(Map<String, String> additionalParams) {
    this.additionalParams = additionalParams;
    return this;
  }

  public BatchLogRequestEntry putAdditionalParamsItem(String key, String additionalParamsItem) {
    if (this.additionalParams == null) {
      this.additionalParams = new HashMap<>();
    }
    this.additionalParams.put(key, additionalParamsItem);
    return this;
  }

   /**
   * Get additionalParams
   * @return additionalParams
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getAdditionalParams() {
    return additionalParams;
  }

  public void setAdditionalParams(Map<String, String> additionalParams) {
    this.additionalParams = additionalParams;
  }

  public BatchLogRequestEntry binaryContent(Boolean binaryContent) {
    this.binaryContent = binaryContent;
    return this;
  }

   /**
   * Get binaryContent
   * @return binaryContent
  **/
  @ApiModelProperty(value = "")
  public Boolean isBinaryContent() {
    return binaryContent;
  }

  public void setBinaryContent(Boolean binaryContent) {
    this.binaryContent = binaryContent;
  }

  public BatchLogRequestEntry encryptedKeywordsList(List<String> encryptedKeywordsList) {
    this.encryptedKeywordsList = encryptedKeywordsList;
    return this;
  }

  public BatchLogRequestEntry addEncryptedKeywordsListItem(String encryptedKeywordsListItem) {
    if (this.encryptedKeywordsList == null) {
      this.encryptedKeywordsList = new ArrayList<>();
    }
    this.encryptedKeywordsList.add(encryptedKeywordsListItem);
    return this;
  }

   /**
   * Get encryptedKeywordsList
   * @return encryptedKeywordsList
  **/
  @ApiModelProperty(value = "")
  public List<String> getEncryptedKeywordsList() {
    return encryptedKeywordsList;
  }

  public void setEncryptedKeywordsList(List<String> encryptedKeywordsList) {
    this.encryptedKeywordsList = encryptedKeywordsList;
  }

  public BatchLogRequestEntry signature(String signature) {
    this.signature = signature;
    return this;
  }

   /**
   * Get signature
   * @return signature
  **/
  @ApiModelProperty(value = "")
  public String getSignature() {
    return signature;
  }

  public void setSignature(String signature) {
    this.signature = signature;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchLogRequestEntry batchLogRequestEntry = (BatchLogRequestEntry) o;
    return Objects.equals(this.actionData, batchLogRequestEntry.actionData) &&
        Objects.equals(this.actorData, batchLogRequestEntry.actorData) &&
        Objects.equals(this.additionalParams, batchLogRequestEntry.additionalParams) &&
        Objects.equals(this.binaryContent, batchLogRequestEntry.binaryContent) &&
        Objects.equals(this.encryptedKeywordsList, batchLogRequestEntry.encryptedKeywordsList) &&
        Objects.equals(this.signature, batchLogRequestEntry.signature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actionData, actorData, additionalParams, binaryContent, encryptedKeywordsList, signature);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchLogRequestEntry {\n");
    
    sb.append("    actionData: ").append(toIndentedString(actionData)).append("\n");
    sb.append("    actorData: ").append(toIndentedString(actorData)).append("\n");
    sb.append("    additionalParams: ").append(toIndentedString(additionalParams)).append("\n");
    sb.append("    binaryContent: ").append(toIndentedString(binaryContent)).append("\n");
    sb.append("    encryptedKeywordsList: ").append(toIndentedString(encryptedKeywordsList)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

