/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * GDPRResponsibleEntity
 */

public class GDPRResponsibleEntity {
  @JsonProperty("aboveGDPREmployeeThreshold")
  private Boolean aboveGDPREmployeeThreshold = null;

  @JsonProperty("address")
  private String address = null;

  @JsonProperty("created")
  private OffsetDateTime created = null;

  @JsonProperty("deleted")
  private Boolean deleted = null;

  @JsonProperty("dpoEmail")
  private String dpoEmail = null;

  @JsonProperty("dpoName")
  private String dpoName = null;

  @JsonProperty("dpoPhone")
  private String dpoPhone = null;

  @JsonProperty("entityName")
  private String entityName = null;

  @JsonProperty("id")
  private UUID id = null;

  /**
   * Gets or Sets legalEntityType
   */
  public enum LegalEntityTypeEnum {
    LEGAL_PERSON("LEGAL_PERSON"),
    
    NATURAL_PERSON("NATURAL_PERSON"),
    
    PUBLIC_AUTHORITY("PUBLIC_AUTHORITY");

    private String value;

    LegalEntityTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LegalEntityTypeEnum fromValue(String text) {
      for (LegalEntityTypeEnum b : LegalEntityTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("legalEntityType")
  private LegalEntityTypeEnum legalEntityType = null;

  @JsonProperty("legalIdentifier")
  private String legalIdentifier = null;

  @JsonProperty("owningOrganizationId")
  private UUID owningOrganizationId = null;

  @JsonProperty("representativeEmail")
  private String representativeEmail = null;

  @JsonProperty("representativeName")
  private String representativeName = null;

  @JsonProperty("representativePhone")
  private String representativePhone = null;

  @JsonProperty("updated")
  private OffsetDateTime updated = null;

  public GDPRResponsibleEntity aboveGDPREmployeeThreshold(Boolean aboveGDPREmployeeThreshold) {
    this.aboveGDPREmployeeThreshold = aboveGDPREmployeeThreshold;
    return this;
  }

   /**
   * Get aboveGDPREmployeeThreshold
   * @return aboveGDPREmployeeThreshold
  **/
  @ApiModelProperty(value = "")
  public Boolean isAboveGDPREmployeeThreshold() {
    return aboveGDPREmployeeThreshold;
  }

  public void setAboveGDPREmployeeThreshold(Boolean aboveGDPREmployeeThreshold) {
    this.aboveGDPREmployeeThreshold = aboveGDPREmployeeThreshold;
  }

  public GDPRResponsibleEntity address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public GDPRResponsibleEntity created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public GDPRResponsibleEntity deleted(Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  @ApiModelProperty(value = "")
  public Boolean isDeleted() {
    return deleted;
  }

  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }

  public GDPRResponsibleEntity dpoEmail(String dpoEmail) {
    this.dpoEmail = dpoEmail;
    return this;
  }

   /**
   * Get dpoEmail
   * @return dpoEmail
  **/
  @ApiModelProperty(value = "")
  public String getDpoEmail() {
    return dpoEmail;
  }

  public void setDpoEmail(String dpoEmail) {
    this.dpoEmail = dpoEmail;
  }

  public GDPRResponsibleEntity dpoName(String dpoName) {
    this.dpoName = dpoName;
    return this;
  }

   /**
   * Get dpoName
   * @return dpoName
  **/
  @ApiModelProperty(value = "")
  public String getDpoName() {
    return dpoName;
  }

  public void setDpoName(String dpoName) {
    this.dpoName = dpoName;
  }

  public GDPRResponsibleEntity dpoPhone(String dpoPhone) {
    this.dpoPhone = dpoPhone;
    return this;
  }

   /**
   * Get dpoPhone
   * @return dpoPhone
  **/
  @ApiModelProperty(value = "")
  public String getDpoPhone() {
    return dpoPhone;
  }

  public void setDpoPhone(String dpoPhone) {
    this.dpoPhone = dpoPhone;
  }

  public GDPRResponsibleEntity entityName(String entityName) {
    this.entityName = entityName;
    return this;
  }

   /**
   * Get entityName
   * @return entityName
  **/
  @ApiModelProperty(value = "")
  public String getEntityName() {
    return entityName;
  }

  public void setEntityName(String entityName) {
    this.entityName = entityName;
  }

  public GDPRResponsibleEntity id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public GDPRResponsibleEntity legalEntityType(LegalEntityTypeEnum legalEntityType) {
    this.legalEntityType = legalEntityType;
    return this;
  }

   /**
   * Get legalEntityType
   * @return legalEntityType
  **/
  @ApiModelProperty(value = "")
  public LegalEntityTypeEnum getLegalEntityType() {
    return legalEntityType;
  }

  public void setLegalEntityType(LegalEntityTypeEnum legalEntityType) {
    this.legalEntityType = legalEntityType;
  }

  public GDPRResponsibleEntity legalIdentifier(String legalIdentifier) {
    this.legalIdentifier = legalIdentifier;
    return this;
  }

   /**
   * Get legalIdentifier
   * @return legalIdentifier
  **/
  @ApiModelProperty(value = "")
  public String getLegalIdentifier() {
    return legalIdentifier;
  }

  public void setLegalIdentifier(String legalIdentifier) {
    this.legalIdentifier = legalIdentifier;
  }

  public GDPRResponsibleEntity owningOrganizationId(UUID owningOrganizationId) {
    this.owningOrganizationId = owningOrganizationId;
    return this;
  }

   /**
   * Get owningOrganizationId
   * @return owningOrganizationId
  **/
  @ApiModelProperty(value = "")
  public UUID getOwningOrganizationId() {
    return owningOrganizationId;
  }

  public void setOwningOrganizationId(UUID owningOrganizationId) {
    this.owningOrganizationId = owningOrganizationId;
  }

  public GDPRResponsibleEntity representativeEmail(String representativeEmail) {
    this.representativeEmail = representativeEmail;
    return this;
  }

   /**
   * Get representativeEmail
   * @return representativeEmail
  **/
  @ApiModelProperty(value = "")
  public String getRepresentativeEmail() {
    return representativeEmail;
  }

  public void setRepresentativeEmail(String representativeEmail) {
    this.representativeEmail = representativeEmail;
  }

  public GDPRResponsibleEntity representativeName(String representativeName) {
    this.representativeName = representativeName;
    return this;
  }

   /**
   * Get representativeName
   * @return representativeName
  **/
  @ApiModelProperty(value = "")
  public String getRepresentativeName() {
    return representativeName;
  }

  public void setRepresentativeName(String representativeName) {
    this.representativeName = representativeName;
  }

  public GDPRResponsibleEntity representativePhone(String representativePhone) {
    this.representativePhone = representativePhone;
    return this;
  }

   /**
   * Get representativePhone
   * @return representativePhone
  **/
  @ApiModelProperty(value = "")
  public String getRepresentativePhone() {
    return representativePhone;
  }

  public void setRepresentativePhone(String representativePhone) {
    this.representativePhone = representativePhone;
  }

  public GDPRResponsibleEntity updated(OffsetDateTime updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Get updated
   * @return updated
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getUpdated() {
    return updated;
  }

  public void setUpdated(OffsetDateTime updated) {
    this.updated = updated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GDPRResponsibleEntity gdPRResponsibleEntity = (GDPRResponsibleEntity) o;
    return Objects.equals(this.aboveGDPREmployeeThreshold, gdPRResponsibleEntity.aboveGDPREmployeeThreshold) &&
        Objects.equals(this.address, gdPRResponsibleEntity.address) &&
        Objects.equals(this.created, gdPRResponsibleEntity.created) &&
        Objects.equals(this.deleted, gdPRResponsibleEntity.deleted) &&
        Objects.equals(this.dpoEmail, gdPRResponsibleEntity.dpoEmail) &&
        Objects.equals(this.dpoName, gdPRResponsibleEntity.dpoName) &&
        Objects.equals(this.dpoPhone, gdPRResponsibleEntity.dpoPhone) &&
        Objects.equals(this.entityName, gdPRResponsibleEntity.entityName) &&
        Objects.equals(this.id, gdPRResponsibleEntity.id) &&
        Objects.equals(this.legalEntityType, gdPRResponsibleEntity.legalEntityType) &&
        Objects.equals(this.legalIdentifier, gdPRResponsibleEntity.legalIdentifier) &&
        Objects.equals(this.owningOrganizationId, gdPRResponsibleEntity.owningOrganizationId) &&
        Objects.equals(this.representativeEmail, gdPRResponsibleEntity.representativeEmail) &&
        Objects.equals(this.representativeName, gdPRResponsibleEntity.representativeName) &&
        Objects.equals(this.representativePhone, gdPRResponsibleEntity.representativePhone) &&
        Objects.equals(this.updated, gdPRResponsibleEntity.updated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aboveGDPREmployeeThreshold, address, created, deleted, dpoEmail, dpoName, dpoPhone, entityName, id, legalEntityType, legalIdentifier, owningOrganizationId, representativeEmail, representativeName, representativePhone, updated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GDPRResponsibleEntity {\n");
    
    sb.append("    aboveGDPREmployeeThreshold: ").append(toIndentedString(aboveGDPREmployeeThreshold)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    dpoEmail: ").append(toIndentedString(dpoEmail)).append("\n");
    sb.append("    dpoName: ").append(toIndentedString(dpoName)).append("\n");
    sb.append("    dpoPhone: ").append(toIndentedString(dpoPhone)).append("\n");
    sb.append("    entityName: ").append(toIndentedString(entityName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    legalEntityType: ").append(toIndentedString(legalEntityType)).append("\n");
    sb.append("    legalIdentifier: ").append(toIndentedString(legalIdentifier)).append("\n");
    sb.append("    owningOrganizationId: ").append(toIndentedString(owningOrganizationId)).append("\n");
    sb.append("    representativeEmail: ").append(toIndentedString(representativeEmail)).append("\n");
    sb.append("    representativeName: ").append(toIndentedString(representativeName)).append("\n");
    sb.append("    representativePhone: ").append(toIndentedString(representativePhone)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

