/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * MerkleTreeInfo
 */

public class MerkleTreeInfo {
  @JsonProperty("hashAlgorithmOid")
  private String hashAlgorithmOid = null;

  @JsonProperty("leafHashAlgorithmOid")
  private String leafHashAlgorithmOid = null;

  @JsonProperty("timestampAlgorithmOid")
  private String timestampAlgorithmOid = null;

  @JsonProperty("timestampPublicKey")
  private String timestampPublicKey = null;

  public MerkleTreeInfo hashAlgorithmOid(String hashAlgorithmOid) {
    this.hashAlgorithmOid = hashAlgorithmOid;
    return this;
  }

   /**
   * Get hashAlgorithmOid
   * @return hashAlgorithmOid
  **/
  @ApiModelProperty(value = "")
  public String getHashAlgorithmOid() {
    return hashAlgorithmOid;
  }

  public void setHashAlgorithmOid(String hashAlgorithmOid) {
    this.hashAlgorithmOid = hashAlgorithmOid;
  }

  public MerkleTreeInfo leafHashAlgorithmOid(String leafHashAlgorithmOid) {
    this.leafHashAlgorithmOid = leafHashAlgorithmOid;
    return this;
  }

   /**
   * Get leafHashAlgorithmOid
   * @return leafHashAlgorithmOid
  **/
  @ApiModelProperty(value = "")
  public String getLeafHashAlgorithmOid() {
    return leafHashAlgorithmOid;
  }

  public void setLeafHashAlgorithmOid(String leafHashAlgorithmOid) {
    this.leafHashAlgorithmOid = leafHashAlgorithmOid;
  }

  public MerkleTreeInfo timestampAlgorithmOid(String timestampAlgorithmOid) {
    this.timestampAlgorithmOid = timestampAlgorithmOid;
    return this;
  }

   /**
   * Get timestampAlgorithmOid
   * @return timestampAlgorithmOid
  **/
  @ApiModelProperty(value = "")
  public String getTimestampAlgorithmOid() {
    return timestampAlgorithmOid;
  }

  public void setTimestampAlgorithmOid(String timestampAlgorithmOid) {
    this.timestampAlgorithmOid = timestampAlgorithmOid;
  }

  public MerkleTreeInfo timestampPublicKey(String timestampPublicKey) {
    this.timestampPublicKey = timestampPublicKey;
    return this;
  }

   /**
   * Get timestampPublicKey
   * @return timestampPublicKey
  **/
  @ApiModelProperty(value = "")
  public String getTimestampPublicKey() {
    return timestampPublicKey;
  }

  public void setTimestampPublicKey(String timestampPublicKey) {
    this.timestampPublicKey = timestampPublicKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerkleTreeInfo merkleTreeInfo = (MerkleTreeInfo) o;
    return Objects.equals(this.hashAlgorithmOid, merkleTreeInfo.hashAlgorithmOid) &&
        Objects.equals(this.leafHashAlgorithmOid, merkleTreeInfo.leafHashAlgorithmOid) &&
        Objects.equals(this.timestampAlgorithmOid, merkleTreeInfo.timestampAlgorithmOid) &&
        Objects.equals(this.timestampPublicKey, merkleTreeInfo.timestampPublicKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashAlgorithmOid, leafHashAlgorithmOid, timestampAlgorithmOid, timestampPublicKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerkleTreeInfo {\n");
    
    sb.append("    hashAlgorithmOid: ").append(toIndentedString(hashAlgorithmOid)).append("\n");
    sb.append("    leafHashAlgorithmOid: ").append(toIndentedString(leafHashAlgorithmOid)).append("\n");
    sb.append("    timestampAlgorithmOid: ").append(toIndentedString(timestampAlgorithmOid)).append("\n");
    sb.append("    timestampPublicKey: ").append(toIndentedString(timestampPublicKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

