/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * MetadataExtractionPaths
 */

public class MetadataExtractionPaths {
  @JsonProperty("actionPaths")
  private List<String> actionPaths = null;

  @JsonProperty("actorDisplayNamePaths")
  private List<String> actorDisplayNamePaths = null;

  @JsonProperty("actorIdPaths")
  private List<String> actorIdPaths = null;

  @JsonProperty("actorRolesPaths")
  private List<String> actorRolesPaths = null;

  @JsonProperty("entityIdPaths")
  private List<String> entityIdPaths = null;

  @JsonProperty("entityTypePaths")
  private List<String> entityTypePaths = null;

  /**
   * Gets or Sets pathType
   */
  public enum PathTypeEnum {
    XPATH("XPATH"),
    
    JSON_PATH("JSON_PATH");

    private String value;

    PathTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PathTypeEnum fromValue(String text) {
      for (PathTypeEnum b : PathTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("pathType")
  private PathTypeEnum pathType = null;

  @JsonProperty("set")
  private Boolean set = null;

  public MetadataExtractionPaths actionPaths(List<String> actionPaths) {
    this.actionPaths = actionPaths;
    return this;
  }

  public MetadataExtractionPaths addActionPathsItem(String actionPathsItem) {
    if (this.actionPaths == null) {
      this.actionPaths = new ArrayList<>();
    }
    this.actionPaths.add(actionPathsItem);
    return this;
  }

   /**
   * Get actionPaths
   * @return actionPaths
  **/
  @ApiModelProperty(value = "")
  public List<String> getActionPaths() {
    return actionPaths;
  }

  public void setActionPaths(List<String> actionPaths) {
    this.actionPaths = actionPaths;
  }

  public MetadataExtractionPaths actorDisplayNamePaths(List<String> actorDisplayNamePaths) {
    this.actorDisplayNamePaths = actorDisplayNamePaths;
    return this;
  }

  public MetadataExtractionPaths addActorDisplayNamePathsItem(String actorDisplayNamePathsItem) {
    if (this.actorDisplayNamePaths == null) {
      this.actorDisplayNamePaths = new ArrayList<>();
    }
    this.actorDisplayNamePaths.add(actorDisplayNamePathsItem);
    return this;
  }

   /**
   * Get actorDisplayNamePaths
   * @return actorDisplayNamePaths
  **/
  @ApiModelProperty(value = "")
  public List<String> getActorDisplayNamePaths() {
    return actorDisplayNamePaths;
  }

  public void setActorDisplayNamePaths(List<String> actorDisplayNamePaths) {
    this.actorDisplayNamePaths = actorDisplayNamePaths;
  }

  public MetadataExtractionPaths actorIdPaths(List<String> actorIdPaths) {
    this.actorIdPaths = actorIdPaths;
    return this;
  }

  public MetadataExtractionPaths addActorIdPathsItem(String actorIdPathsItem) {
    if (this.actorIdPaths == null) {
      this.actorIdPaths = new ArrayList<>();
    }
    this.actorIdPaths.add(actorIdPathsItem);
    return this;
  }

   /**
   * Get actorIdPaths
   * @return actorIdPaths
  **/
  @ApiModelProperty(value = "")
  public List<String> getActorIdPaths() {
    return actorIdPaths;
  }

  public void setActorIdPaths(List<String> actorIdPaths) {
    this.actorIdPaths = actorIdPaths;
  }

  public MetadataExtractionPaths actorRolesPaths(List<String> actorRolesPaths) {
    this.actorRolesPaths = actorRolesPaths;
    return this;
  }

  public MetadataExtractionPaths addActorRolesPathsItem(String actorRolesPathsItem) {
    if (this.actorRolesPaths == null) {
      this.actorRolesPaths = new ArrayList<>();
    }
    this.actorRolesPaths.add(actorRolesPathsItem);
    return this;
  }

   /**
   * Get actorRolesPaths
   * @return actorRolesPaths
  **/
  @ApiModelProperty(value = "")
  public List<String> getActorRolesPaths() {
    return actorRolesPaths;
  }

  public void setActorRolesPaths(List<String> actorRolesPaths) {
    this.actorRolesPaths = actorRolesPaths;
  }

  public MetadataExtractionPaths entityIdPaths(List<String> entityIdPaths) {
    this.entityIdPaths = entityIdPaths;
    return this;
  }

  public MetadataExtractionPaths addEntityIdPathsItem(String entityIdPathsItem) {
    if (this.entityIdPaths == null) {
      this.entityIdPaths = new ArrayList<>();
    }
    this.entityIdPaths.add(entityIdPathsItem);
    return this;
  }

   /**
   * Get entityIdPaths
   * @return entityIdPaths
  **/
  @ApiModelProperty(value = "")
  public List<String> getEntityIdPaths() {
    return entityIdPaths;
  }

  public void setEntityIdPaths(List<String> entityIdPaths) {
    this.entityIdPaths = entityIdPaths;
  }

  public MetadataExtractionPaths entityTypePaths(List<String> entityTypePaths) {
    this.entityTypePaths = entityTypePaths;
    return this;
  }

  public MetadataExtractionPaths addEntityTypePathsItem(String entityTypePathsItem) {
    if (this.entityTypePaths == null) {
      this.entityTypePaths = new ArrayList<>();
    }
    this.entityTypePaths.add(entityTypePathsItem);
    return this;
  }

   /**
   * Get entityTypePaths
   * @return entityTypePaths
  **/
  @ApiModelProperty(value = "")
  public List<String> getEntityTypePaths() {
    return entityTypePaths;
  }

  public void setEntityTypePaths(List<String> entityTypePaths) {
    this.entityTypePaths = entityTypePaths;
  }

  public MetadataExtractionPaths pathType(PathTypeEnum pathType) {
    this.pathType = pathType;
    return this;
  }

   /**
   * Get pathType
   * @return pathType
  **/
  @ApiModelProperty(value = "")
  public PathTypeEnum getPathType() {
    return pathType;
  }

  public void setPathType(PathTypeEnum pathType) {
    this.pathType = pathType;
  }

  public MetadataExtractionPaths set(Boolean set) {
    this.set = set;
    return this;
  }

   /**
   * Get set
   * @return set
  **/
  @ApiModelProperty(value = "")
  public Boolean isSet() {
    return set;
  }

  public void setSet(Boolean set) {
    this.set = set;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetadataExtractionPaths metadataExtractionPaths = (MetadataExtractionPaths) o;
    return Objects.equals(this.actionPaths, metadataExtractionPaths.actionPaths) &&
        Objects.equals(this.actorDisplayNamePaths, metadataExtractionPaths.actorDisplayNamePaths) &&
        Objects.equals(this.actorIdPaths, metadataExtractionPaths.actorIdPaths) &&
        Objects.equals(this.actorRolesPaths, metadataExtractionPaths.actorRolesPaths) &&
        Objects.equals(this.entityIdPaths, metadataExtractionPaths.entityIdPaths) &&
        Objects.equals(this.entityTypePaths, metadataExtractionPaths.entityTypePaths) &&
        Objects.equals(this.pathType, metadataExtractionPaths.pathType) &&
        Objects.equals(this.set, metadataExtractionPaths.set);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actionPaths, actorDisplayNamePaths, actorIdPaths, actorRolesPaths, entityIdPaths, entityTypePaths, pathType, set);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetadataExtractionPaths {\n");
    
    sb.append("    actionPaths: ").append(toIndentedString(actionPaths)).append("\n");
    sb.append("    actorDisplayNamePaths: ").append(toIndentedString(actorDisplayNamePaths)).append("\n");
    sb.append("    actorIdPaths: ").append(toIndentedString(actorIdPaths)).append("\n");
    sb.append("    actorRolesPaths: ").append(toIndentedString(actorRolesPaths)).append("\n");
    sb.append("    entityIdPaths: ").append(toIndentedString(entityIdPaths)).append("\n");
    sb.append("    entityTypePaths: ").append(toIndentedString(entityTypePaths)).append("\n");
    sb.append("    pathType: ").append(toIndentedString(pathType)).append("\n");
    sb.append("    set: ").append(toIndentedString(set)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

