/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.logsentinel.model.ResolvedVerificationFailure;
import com.logsentinel.model.Verification;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ResolvedVerificationFailureResponse
 */

public class ResolvedVerificationFailureResponse {
  @JsonProperty("resolution")
  private ResolvedVerificationFailure resolution = null;

  @JsonProperty("verification")
  private Verification verification = null;

  public ResolvedVerificationFailureResponse resolution(ResolvedVerificationFailure resolution) {
    this.resolution = resolution;
    return this;
  }

   /**
   * Get resolution
   * @return resolution
  **/
  @ApiModelProperty(value = "")
  public ResolvedVerificationFailure getResolution() {
    return resolution;
  }

  public void setResolution(ResolvedVerificationFailure resolution) {
    this.resolution = resolution;
  }

  public ResolvedVerificationFailureResponse verification(Verification verification) {
    this.verification = verification;
    return this;
  }

   /**
   * Get verification
   * @return verification
  **/
  @ApiModelProperty(value = "")
  public Verification getVerification() {
    return verification;
  }

  public void setVerification(Verification verification) {
    this.verification = verification;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResolvedVerificationFailureResponse resolvedVerificationFailureResponse = (ResolvedVerificationFailureResponse) o;
    return Objects.equals(this.resolution, resolvedVerificationFailureResponse.resolution) &&
        Objects.equals(this.verification, resolvedVerificationFailureResponse.verification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resolution, verification);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResolvedVerificationFailureResponse {\n");
    
    sb.append("    resolution: ").append(toIndentedString(resolution)).append("\n");
    sb.append("    verification: ").append(toIndentedString(verification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

