/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * ResolvedVerificationFailure
 */

public class ResolvedVerificationFailure {
  @JsonProperty("created")
  private OffsetDateTime created = null;

  @JsonProperty("id")
  private UUID id = null;

  @JsonProperty("reason")
  private String reason = null;

  @JsonProperty("resolvingUserId")
  private UUID resolvingUserId = null;

  @JsonProperty("verificationId")
  private UUID verificationId = null;

  public ResolvedVerificationFailure created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public ResolvedVerificationFailure id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public ResolvedVerificationFailure reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @ApiModelProperty(value = "")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public ResolvedVerificationFailure resolvingUserId(UUID resolvingUserId) {
    this.resolvingUserId = resolvingUserId;
    return this;
  }

   /**
   * Get resolvingUserId
   * @return resolvingUserId
  **/
  @ApiModelProperty(value = "")
  public UUID getResolvingUserId() {
    return resolvingUserId;
  }

  public void setResolvingUserId(UUID resolvingUserId) {
    this.resolvingUserId = resolvingUserId;
  }

  public ResolvedVerificationFailure verificationId(UUID verificationId) {
    this.verificationId = verificationId;
    return this;
  }

   /**
   * Get verificationId
   * @return verificationId
  **/
  @ApiModelProperty(value = "")
  public UUID getVerificationId() {
    return verificationId;
  }

  public void setVerificationId(UUID verificationId) {
    this.verificationId = verificationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResolvedVerificationFailure resolvedVerificationFailure = (ResolvedVerificationFailure) o;
    return Objects.equals(this.created, resolvedVerificationFailure.created) &&
        Objects.equals(this.id, resolvedVerificationFailure.id) &&
        Objects.equals(this.reason, resolvedVerificationFailure.reason) &&
        Objects.equals(this.resolvingUserId, resolvedVerificationFailure.resolvingUserId) &&
        Objects.equals(this.verificationId, resolvedVerificationFailure.verificationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, id, reason, resolvingUserId, verificationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResolvedVerificationFailure {\n");
    
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    resolvingUserId: ").append(toIndentedString(resolvingUserId)).append("\n");
    sb.append("    verificationId: ").append(toIndentedString(verificationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

