/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;

/**
 * UpdateUserRequest
 */

public class UpdateUserRequest {
  @JsonProperty("email")
  private String email = null;

  /**
   * Gets or Sets language
   */
  public enum LanguageEnum {
    EN("EN"),
    
    BG("BG");

    private String value;

    LanguageEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LanguageEnum fromValue(String text) {
      for (LanguageEnum b : LanguageEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("language")
  private LanguageEnum language = null;

  @JsonProperty("names")
  private String names = null;

  @JsonProperty("position")
  private String position = null;

  @JsonProperty("profilePicturePath")
  private String profilePicturePath = null;

  @JsonProperty("receiveUpdates")
  private Boolean receiveUpdates = null;

  @JsonProperty("timezone")
  private String timezone = null;

  @JsonProperty("userId")
  private UUID userId = null;

  public UpdateUserRequest email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UpdateUserRequest language(LanguageEnum language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @ApiModelProperty(value = "")
  public LanguageEnum getLanguage() {
    return language;
  }

  public void setLanguage(LanguageEnum language) {
    this.language = language;
  }

  public UpdateUserRequest names(String names) {
    this.names = names;
    return this;
  }

   /**
   * Get names
   * @return names
  **/
  @ApiModelProperty(value = "")
  public String getNames() {
    return names;
  }

  public void setNames(String names) {
    this.names = names;
  }

  public UpdateUserRequest position(String position) {
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @ApiModelProperty(value = "")
  public String getPosition() {
    return position;
  }

  public void setPosition(String position) {
    this.position = position;
  }

  public UpdateUserRequest profilePicturePath(String profilePicturePath) {
    this.profilePicturePath = profilePicturePath;
    return this;
  }

   /**
   * Get profilePicturePath
   * @return profilePicturePath
  **/
  @ApiModelProperty(value = "")
  public String getProfilePicturePath() {
    return profilePicturePath;
  }

  public void setProfilePicturePath(String profilePicturePath) {
    this.profilePicturePath = profilePicturePath;
  }

  public UpdateUserRequest receiveUpdates(Boolean receiveUpdates) {
    this.receiveUpdates = receiveUpdates;
    return this;
  }

   /**
   * Get receiveUpdates
   * @return receiveUpdates
  **/
  @ApiModelProperty(value = "")
  public Boolean isReceiveUpdates() {
    return receiveUpdates;
  }

  public void setReceiveUpdates(Boolean receiveUpdates) {
    this.receiveUpdates = receiveUpdates;
  }

  public UpdateUserRequest timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Get timezone
   * @return timezone
  **/
  @ApiModelProperty(value = "")
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }

  public UpdateUserRequest userId(UUID userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public UUID getUserId() {
    return userId;
  }

  public void setUserId(UUID userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateUserRequest updateUserRequest = (UpdateUserRequest) o;
    return Objects.equals(this.email, updateUserRequest.email) &&
        Objects.equals(this.language, updateUserRequest.language) &&
        Objects.equals(this.names, updateUserRequest.names) &&
        Objects.equals(this.position, updateUserRequest.position) &&
        Objects.equals(this.profilePicturePath, updateUserRequest.profilePicturePath) &&
        Objects.equals(this.receiveUpdates, updateUserRequest.receiveUpdates) &&
        Objects.equals(this.timezone, updateUserRequest.timezone) &&
        Objects.equals(this.userId, updateUserRequest.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, language, names, position, profilePicturePath, receiveUpdates, timezone, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateUserRequest {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    names: ").append(toIndentedString(names)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    profilePicturePath: ").append(toIndentedString(profilePicturePath)).append("\n");
    sb.append("    receiveUpdates: ").append(toIndentedString(receiveUpdates)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

