/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.logsentinel.model.MetadataExtractionPaths;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * UpdateApplicationRequest
 */

public class UpdateApplicationRequest {
  @JsonProperty("containsPersonalData")
  private Boolean containsPersonalData = null;

  @JsonProperty("detailsTransformationScript")
  private String detailsTransformationScript = null;

  @JsonProperty("displayedDetailsFields")
  private String displayedDetailsFields = null;

  @JsonProperty("id")
  private UUID id = null;

  @JsonProperty("ipWhiteList")
  private List<String> ipWhiteList = null;

  @JsonProperty("latestHashRecipientEmails")
  private List<String> latestHashRecipientEmails = null;

  @JsonProperty("logLevelErrorReportRecipientEmails")
  private List<String> logLevelErrorReportRecipientEmails = null;

  @JsonProperty("logLevelRegexes")
  private Map<String, String> logLevelRegexes = null;

  @JsonProperty("metadataExtractionPaths")
  private MetadataExtractionPaths metadataExtractionPaths = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("openDataAnonymizationRegexes")
  private List<String> openDataAnonymizationRegexes = null;

  @JsonProperty("openDataAnonymizeBodyFields")
  private List<String> openDataAnonymizeBodyFields = null;

  @JsonProperty("openDataEnabled")
  private Boolean openDataEnabled = null;

  @JsonProperty("openDataWhitelistRegexes")
  private List<String> openDataWhitelistRegexes = null;

  @JsonProperty("partialVerificationPeriodMinutes")
  private Integer partialVerificationPeriodMinutes = null;

  @JsonProperty("signatureVerificationPublicKeys")
  private List<String> signatureVerificationPublicKeys = null;

  @JsonProperty("storeHashesInEthereum")
  private Boolean storeHashesInEthereum = null;

  @JsonProperty("verificationFailureReportRecipientEmails")
  private List<String> verificationFailureReportRecipientEmails = null;

  @JsonProperty("verificationPeriodMinutes")
  private Integer verificationPeriodMinutes = null;

  /**
   * Gets or Sets warnLevel
   */
  public enum WarnLevelEnum {
    TRACE("TRACE"),
    
    DEBUG("DEBUG"),
    
    INFO("INFO"),
    
    WARN("WARN"),
    
    ERROR("ERROR"),
    
    CRITICAL("CRITICAL"),
    
    FATAL("FATAL");

    private String value;

    WarnLevelEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static WarnLevelEnum fromValue(String text) {
      for (WarnLevelEnum b : WarnLevelEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("warnLevel")
  private WarnLevelEnum warnLevel = null;

  public UpdateApplicationRequest containsPersonalData(Boolean containsPersonalData) {
    this.containsPersonalData = containsPersonalData;
    return this;
  }

   /**
   * Get containsPersonalData
   * @return containsPersonalData
  **/
  @ApiModelProperty(value = "")
  public Boolean isContainsPersonalData() {
    return containsPersonalData;
  }

  public void setContainsPersonalData(Boolean containsPersonalData) {
    this.containsPersonalData = containsPersonalData;
  }

  public UpdateApplicationRequest detailsTransformationScript(String detailsTransformationScript) {
    this.detailsTransformationScript = detailsTransformationScript;
    return this;
  }

   /**
   * Get detailsTransformationScript
   * @return detailsTransformationScript
  **/
  @ApiModelProperty(value = "")
  public String getDetailsTransformationScript() {
    return detailsTransformationScript;
  }

  public void setDetailsTransformationScript(String detailsTransformationScript) {
    this.detailsTransformationScript = detailsTransformationScript;
  }

  public UpdateApplicationRequest displayedDetailsFields(String displayedDetailsFields) {
    this.displayedDetailsFields = displayedDetailsFields;
    return this;
  }

   /**
   * Get displayedDetailsFields
   * @return displayedDetailsFields
  **/
  @ApiModelProperty(value = "")
  public String getDisplayedDetailsFields() {
    return displayedDetailsFields;
  }

  public void setDisplayedDetailsFields(String displayedDetailsFields) {
    this.displayedDetailsFields = displayedDetailsFields;
  }

  public UpdateApplicationRequest id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public UpdateApplicationRequest ipWhiteList(List<String> ipWhiteList) {
    this.ipWhiteList = ipWhiteList;
    return this;
  }

  public UpdateApplicationRequest addIpWhiteListItem(String ipWhiteListItem) {
    if (this.ipWhiteList == null) {
      this.ipWhiteList = new ArrayList<>();
    }
    this.ipWhiteList.add(ipWhiteListItem);
    return this;
  }

   /**
   * Get ipWhiteList
   * @return ipWhiteList
  **/
  @ApiModelProperty(value = "")
  public List<String> getIpWhiteList() {
    return ipWhiteList;
  }

  public void setIpWhiteList(List<String> ipWhiteList) {
    this.ipWhiteList = ipWhiteList;
  }

  public UpdateApplicationRequest latestHashRecipientEmails(List<String> latestHashRecipientEmails) {
    this.latestHashRecipientEmails = latestHashRecipientEmails;
    return this;
  }

  public UpdateApplicationRequest addLatestHashRecipientEmailsItem(String latestHashRecipientEmailsItem) {
    if (this.latestHashRecipientEmails == null) {
      this.latestHashRecipientEmails = new ArrayList<>();
    }
    this.latestHashRecipientEmails.add(latestHashRecipientEmailsItem);
    return this;
  }

   /**
   * Get latestHashRecipientEmails
   * @return latestHashRecipientEmails
  **/
  @ApiModelProperty(value = "")
  public List<String> getLatestHashRecipientEmails() {
    return latestHashRecipientEmails;
  }

  public void setLatestHashRecipientEmails(List<String> latestHashRecipientEmails) {
    this.latestHashRecipientEmails = latestHashRecipientEmails;
  }

  public UpdateApplicationRequest logLevelErrorReportRecipientEmails(List<String> logLevelErrorReportRecipientEmails) {
    this.logLevelErrorReportRecipientEmails = logLevelErrorReportRecipientEmails;
    return this;
  }

  public UpdateApplicationRequest addLogLevelErrorReportRecipientEmailsItem(String logLevelErrorReportRecipientEmailsItem) {
    if (this.logLevelErrorReportRecipientEmails == null) {
      this.logLevelErrorReportRecipientEmails = new ArrayList<>();
    }
    this.logLevelErrorReportRecipientEmails.add(logLevelErrorReportRecipientEmailsItem);
    return this;
  }

   /**
   * Get logLevelErrorReportRecipientEmails
   * @return logLevelErrorReportRecipientEmails
  **/
  @ApiModelProperty(value = "")
  public List<String> getLogLevelErrorReportRecipientEmails() {
    return logLevelErrorReportRecipientEmails;
  }

  public void setLogLevelErrorReportRecipientEmails(List<String> logLevelErrorReportRecipientEmails) {
    this.logLevelErrorReportRecipientEmails = logLevelErrorReportRecipientEmails;
  }

  public UpdateApplicationRequest logLevelRegexes(Map<String, String> logLevelRegexes) {
    this.logLevelRegexes = logLevelRegexes;
    return this;
  }

  public UpdateApplicationRequest putLogLevelRegexesItem(String key, String logLevelRegexesItem) {
    if (this.logLevelRegexes == null) {
      this.logLevelRegexes = new HashMap<>();
    }
    this.logLevelRegexes.put(key, logLevelRegexesItem);
    return this;
  }

   /**
   * Get logLevelRegexes
   * @return logLevelRegexes
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getLogLevelRegexes() {
    return logLevelRegexes;
  }

  public void setLogLevelRegexes(Map<String, String> logLevelRegexes) {
    this.logLevelRegexes = logLevelRegexes;
  }

  public UpdateApplicationRequest metadataExtractionPaths(MetadataExtractionPaths metadataExtractionPaths) {
    this.metadataExtractionPaths = metadataExtractionPaths;
    return this;
  }

   /**
   * Get metadataExtractionPaths
   * @return metadataExtractionPaths
  **/
  @ApiModelProperty(value = "")
  public MetadataExtractionPaths getMetadataExtractionPaths() {
    return metadataExtractionPaths;
  }

  public void setMetadataExtractionPaths(MetadataExtractionPaths metadataExtractionPaths) {
    this.metadataExtractionPaths = metadataExtractionPaths;
  }

  public UpdateApplicationRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UpdateApplicationRequest openDataAnonymizationRegexes(List<String> openDataAnonymizationRegexes) {
    this.openDataAnonymizationRegexes = openDataAnonymizationRegexes;
    return this;
  }

  public UpdateApplicationRequest addOpenDataAnonymizationRegexesItem(String openDataAnonymizationRegexesItem) {
    if (this.openDataAnonymizationRegexes == null) {
      this.openDataAnonymizationRegexes = new ArrayList<>();
    }
    this.openDataAnonymizationRegexes.add(openDataAnonymizationRegexesItem);
    return this;
  }

   /**
   * Get openDataAnonymizationRegexes
   * @return openDataAnonymizationRegexes
  **/
  @ApiModelProperty(value = "")
  public List<String> getOpenDataAnonymizationRegexes() {
    return openDataAnonymizationRegexes;
  }

  public void setOpenDataAnonymizationRegexes(List<String> openDataAnonymizationRegexes) {
    this.openDataAnonymizationRegexes = openDataAnonymizationRegexes;
  }

  public UpdateApplicationRequest openDataAnonymizeBodyFields(List<String> openDataAnonymizeBodyFields) {
    this.openDataAnonymizeBodyFields = openDataAnonymizeBodyFields;
    return this;
  }

  public UpdateApplicationRequest addOpenDataAnonymizeBodyFieldsItem(String openDataAnonymizeBodyFieldsItem) {
    if (this.openDataAnonymizeBodyFields == null) {
      this.openDataAnonymizeBodyFields = new ArrayList<>();
    }
    this.openDataAnonymizeBodyFields.add(openDataAnonymizeBodyFieldsItem);
    return this;
  }

   /**
   * Get openDataAnonymizeBodyFields
   * @return openDataAnonymizeBodyFields
  **/
  @ApiModelProperty(value = "")
  public List<String> getOpenDataAnonymizeBodyFields() {
    return openDataAnonymizeBodyFields;
  }

  public void setOpenDataAnonymizeBodyFields(List<String> openDataAnonymizeBodyFields) {
    this.openDataAnonymizeBodyFields = openDataAnonymizeBodyFields;
  }

  public UpdateApplicationRequest openDataEnabled(Boolean openDataEnabled) {
    this.openDataEnabled = openDataEnabled;
    return this;
  }

   /**
   * Get openDataEnabled
   * @return openDataEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isOpenDataEnabled() {
    return openDataEnabled;
  }

  public void setOpenDataEnabled(Boolean openDataEnabled) {
    this.openDataEnabled = openDataEnabled;
  }

  public UpdateApplicationRequest openDataWhitelistRegexes(List<String> openDataWhitelistRegexes) {
    this.openDataWhitelistRegexes = openDataWhitelistRegexes;
    return this;
  }

  public UpdateApplicationRequest addOpenDataWhitelistRegexesItem(String openDataWhitelistRegexesItem) {
    if (this.openDataWhitelistRegexes == null) {
      this.openDataWhitelistRegexes = new ArrayList<>();
    }
    this.openDataWhitelistRegexes.add(openDataWhitelistRegexesItem);
    return this;
  }

   /**
   * Get openDataWhitelistRegexes
   * @return openDataWhitelistRegexes
  **/
  @ApiModelProperty(value = "")
  public List<String> getOpenDataWhitelistRegexes() {
    return openDataWhitelistRegexes;
  }

  public void setOpenDataWhitelistRegexes(List<String> openDataWhitelistRegexes) {
    this.openDataWhitelistRegexes = openDataWhitelistRegexes;
  }

  public UpdateApplicationRequest partialVerificationPeriodMinutes(Integer partialVerificationPeriodMinutes) {
    this.partialVerificationPeriodMinutes = partialVerificationPeriodMinutes;
    return this;
  }

   /**
   * Get partialVerificationPeriodMinutes
   * @return partialVerificationPeriodMinutes
  **/
  @ApiModelProperty(value = "")
  public Integer getPartialVerificationPeriodMinutes() {
    return partialVerificationPeriodMinutes;
  }

  public void setPartialVerificationPeriodMinutes(Integer partialVerificationPeriodMinutes) {
    this.partialVerificationPeriodMinutes = partialVerificationPeriodMinutes;
  }

  public UpdateApplicationRequest signatureVerificationPublicKeys(List<String> signatureVerificationPublicKeys) {
    this.signatureVerificationPublicKeys = signatureVerificationPublicKeys;
    return this;
  }

  public UpdateApplicationRequest addSignatureVerificationPublicKeysItem(String signatureVerificationPublicKeysItem) {
    if (this.signatureVerificationPublicKeys == null) {
      this.signatureVerificationPublicKeys = new ArrayList<>();
    }
    this.signatureVerificationPublicKeys.add(signatureVerificationPublicKeysItem);
    return this;
  }

   /**
   * Get signatureVerificationPublicKeys
   * @return signatureVerificationPublicKeys
  **/
  @ApiModelProperty(value = "")
  public List<String> getSignatureVerificationPublicKeys() {
    return signatureVerificationPublicKeys;
  }

  public void setSignatureVerificationPublicKeys(List<String> signatureVerificationPublicKeys) {
    this.signatureVerificationPublicKeys = signatureVerificationPublicKeys;
  }

  public UpdateApplicationRequest storeHashesInEthereum(Boolean storeHashesInEthereum) {
    this.storeHashesInEthereum = storeHashesInEthereum;
    return this;
  }

   /**
   * Get storeHashesInEthereum
   * @return storeHashesInEthereum
  **/
  @ApiModelProperty(value = "")
  public Boolean isStoreHashesInEthereum() {
    return storeHashesInEthereum;
  }

  public void setStoreHashesInEthereum(Boolean storeHashesInEthereum) {
    this.storeHashesInEthereum = storeHashesInEthereum;
  }

  public UpdateApplicationRequest verificationFailureReportRecipientEmails(List<String> verificationFailureReportRecipientEmails) {
    this.verificationFailureReportRecipientEmails = verificationFailureReportRecipientEmails;
    return this;
  }

  public UpdateApplicationRequest addVerificationFailureReportRecipientEmailsItem(String verificationFailureReportRecipientEmailsItem) {
    if (this.verificationFailureReportRecipientEmails == null) {
      this.verificationFailureReportRecipientEmails = new ArrayList<>();
    }
    this.verificationFailureReportRecipientEmails.add(verificationFailureReportRecipientEmailsItem);
    return this;
  }

   /**
   * Get verificationFailureReportRecipientEmails
   * @return verificationFailureReportRecipientEmails
  **/
  @ApiModelProperty(value = "")
  public List<String> getVerificationFailureReportRecipientEmails() {
    return verificationFailureReportRecipientEmails;
  }

  public void setVerificationFailureReportRecipientEmails(List<String> verificationFailureReportRecipientEmails) {
    this.verificationFailureReportRecipientEmails = verificationFailureReportRecipientEmails;
  }

  public UpdateApplicationRequest verificationPeriodMinutes(Integer verificationPeriodMinutes) {
    this.verificationPeriodMinutes = verificationPeriodMinutes;
    return this;
  }

   /**
   * Get verificationPeriodMinutes
   * @return verificationPeriodMinutes
  **/
  @ApiModelProperty(value = "")
  public Integer getVerificationPeriodMinutes() {
    return verificationPeriodMinutes;
  }

  public void setVerificationPeriodMinutes(Integer verificationPeriodMinutes) {
    this.verificationPeriodMinutes = verificationPeriodMinutes;
  }

  public UpdateApplicationRequest warnLevel(WarnLevelEnum warnLevel) {
    this.warnLevel = warnLevel;
    return this;
  }

   /**
   * Get warnLevel
   * @return warnLevel
  **/
  @ApiModelProperty(value = "")
  public WarnLevelEnum getWarnLevel() {
    return warnLevel;
  }

  public void setWarnLevel(WarnLevelEnum warnLevel) {
    this.warnLevel = warnLevel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateApplicationRequest updateApplicationRequest = (UpdateApplicationRequest) o;
    return Objects.equals(this.containsPersonalData, updateApplicationRequest.containsPersonalData) &&
        Objects.equals(this.detailsTransformationScript, updateApplicationRequest.detailsTransformationScript) &&
        Objects.equals(this.displayedDetailsFields, updateApplicationRequest.displayedDetailsFields) &&
        Objects.equals(this.id, updateApplicationRequest.id) &&
        Objects.equals(this.ipWhiteList, updateApplicationRequest.ipWhiteList) &&
        Objects.equals(this.latestHashRecipientEmails, updateApplicationRequest.latestHashRecipientEmails) &&
        Objects.equals(this.logLevelErrorReportRecipientEmails, updateApplicationRequest.logLevelErrorReportRecipientEmails) &&
        Objects.equals(this.logLevelRegexes, updateApplicationRequest.logLevelRegexes) &&
        Objects.equals(this.metadataExtractionPaths, updateApplicationRequest.metadataExtractionPaths) &&
        Objects.equals(this.name, updateApplicationRequest.name) &&
        Objects.equals(this.openDataAnonymizationRegexes, updateApplicationRequest.openDataAnonymizationRegexes) &&
        Objects.equals(this.openDataAnonymizeBodyFields, updateApplicationRequest.openDataAnonymizeBodyFields) &&
        Objects.equals(this.openDataEnabled, updateApplicationRequest.openDataEnabled) &&
        Objects.equals(this.openDataWhitelistRegexes, updateApplicationRequest.openDataWhitelistRegexes) &&
        Objects.equals(this.partialVerificationPeriodMinutes, updateApplicationRequest.partialVerificationPeriodMinutes) &&
        Objects.equals(this.signatureVerificationPublicKeys, updateApplicationRequest.signatureVerificationPublicKeys) &&
        Objects.equals(this.storeHashesInEthereum, updateApplicationRequest.storeHashesInEthereum) &&
        Objects.equals(this.verificationFailureReportRecipientEmails, updateApplicationRequest.verificationFailureReportRecipientEmails) &&
        Objects.equals(this.verificationPeriodMinutes, updateApplicationRequest.verificationPeriodMinutes) &&
        Objects.equals(this.warnLevel, updateApplicationRequest.warnLevel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(containsPersonalData, detailsTransformationScript, displayedDetailsFields, id, ipWhiteList, latestHashRecipientEmails, logLevelErrorReportRecipientEmails, logLevelRegexes, metadataExtractionPaths, name, openDataAnonymizationRegexes, openDataAnonymizeBodyFields, openDataEnabled, openDataWhitelistRegexes, partialVerificationPeriodMinutes, signatureVerificationPublicKeys, storeHashesInEthereum, verificationFailureReportRecipientEmails, verificationPeriodMinutes, warnLevel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateApplicationRequest {\n");
    
    sb.append("    containsPersonalData: ").append(toIndentedString(containsPersonalData)).append("\n");
    sb.append("    detailsTransformationScript: ").append(toIndentedString(detailsTransformationScript)).append("\n");
    sb.append("    displayedDetailsFields: ").append(toIndentedString(displayedDetailsFields)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ipWhiteList: ").append(toIndentedString(ipWhiteList)).append("\n");
    sb.append("    latestHashRecipientEmails: ").append(toIndentedString(latestHashRecipientEmails)).append("\n");
    sb.append("    logLevelErrorReportRecipientEmails: ").append(toIndentedString(logLevelErrorReportRecipientEmails)).append("\n");
    sb.append("    logLevelRegexes: ").append(toIndentedString(logLevelRegexes)).append("\n");
    sb.append("    metadataExtractionPaths: ").append(toIndentedString(metadataExtractionPaths)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    openDataAnonymizationRegexes: ").append(toIndentedString(openDataAnonymizationRegexes)).append("\n");
    sb.append("    openDataAnonymizeBodyFields: ").append(toIndentedString(openDataAnonymizeBodyFields)).append("\n");
    sb.append("    openDataEnabled: ").append(toIndentedString(openDataEnabled)).append("\n");
    sb.append("    openDataWhitelistRegexes: ").append(toIndentedString(openDataWhitelistRegexes)).append("\n");
    sb.append("    partialVerificationPeriodMinutes: ").append(toIndentedString(partialVerificationPeriodMinutes)).append("\n");
    sb.append("    signatureVerificationPublicKeys: ").append(toIndentedString(signatureVerificationPublicKeys)).append("\n");
    sb.append("    storeHashesInEthereum: ").append(toIndentedString(storeHashesInEthereum)).append("\n");
    sb.append("    verificationFailureReportRecipientEmails: ").append(toIndentedString(verificationFailureReportRecipientEmails)).append("\n");
    sb.append("    verificationPeriodMinutes: ").append(toIndentedString(verificationPeriodMinutes)).append("\n");
    sb.append("    warnLevel: ").append(toIndentedString(warnLevel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

