/*
 * LogSentinel RESTful API
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.logsentinel.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * UserRegistrationRequest
 */

public class UserRegistrationRequest {
  @JsonProperty("allowedApplicationIds")
  private List<UUID> allowedApplicationIds = null;

  @JsonProperty("attributes")
  private Map<String, String> attributes = null;

  @JsonProperty("awsCustomerId")
  private String awsCustomerId = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("expirationDate")
  private String expirationDate = null;

  @JsonProperty("names")
  private String names = null;

  @JsonProperty("organizationName")
  private String organizationName = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("position")
  private String position = null;

  /**
   * Gets or Sets role
   */
  public enum RoleEnum {
    ADMIN("ADMIN"),
    
    AUDITOR("AUDITOR"),
    
    DEVELOPER("DEVELOPER"),
    
    MANAGER("MANAGER"),
    
    IT("IT"),
    
    PUBLIC_USER("PUBLIC_USER");

    private String value;

    RoleEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RoleEnum fromValue(String text) {
      for (RoleEnum b : RoleEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("role")
  private RoleEnum role = null;

  @JsonProperty("serverName")
  private String serverName = null;

  @JsonProperty("subscriptionPlanCode")
  private String subscriptionPlanCode = null;

  @JsonProperty("timezone")
  private String timezone = null;

  public UserRegistrationRequest allowedApplicationIds(List<UUID> allowedApplicationIds) {
    this.allowedApplicationIds = allowedApplicationIds;
    return this;
  }

  public UserRegistrationRequest addAllowedApplicationIdsItem(UUID allowedApplicationIdsItem) {
    if (this.allowedApplicationIds == null) {
      this.allowedApplicationIds = new ArrayList<>();
    }
    this.allowedApplicationIds.add(allowedApplicationIdsItem);
    return this;
  }

   /**
   * Get allowedApplicationIds
   * @return allowedApplicationIds
  **/
  @ApiModelProperty(value = "")
  public List<UUID> getAllowedApplicationIds() {
    return allowedApplicationIds;
  }

  public void setAllowedApplicationIds(List<UUID> allowedApplicationIds) {
    this.allowedApplicationIds = allowedApplicationIds;
  }

  public UserRegistrationRequest attributes(Map<String, String> attributes) {
    this.attributes = attributes;
    return this;
  }

  public UserRegistrationRequest putAttributesItem(String key, String attributesItem) {
    if (this.attributes == null) {
      this.attributes = new HashMap<>();
    }
    this.attributes.put(key, attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getAttributes() {
    return attributes;
  }

  public void setAttributes(Map<String, String> attributes) {
    this.attributes = attributes;
  }

  public UserRegistrationRequest awsCustomerId(String awsCustomerId) {
    this.awsCustomerId = awsCustomerId;
    return this;
  }

   /**
   * Get awsCustomerId
   * @return awsCustomerId
  **/
  @ApiModelProperty(value = "")
  public String getAwsCustomerId() {
    return awsCustomerId;
  }

  public void setAwsCustomerId(String awsCustomerId) {
    this.awsCustomerId = awsCustomerId;
  }

  public UserRegistrationRequest email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserRegistrationRequest expirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Get expirationDate
   * @return expirationDate
  **/
  @ApiModelProperty(value = "")
  public String getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
  }

  public UserRegistrationRequest names(String names) {
    this.names = names;
    return this;
  }

   /**
   * Get names
   * @return names
  **/
  @ApiModelProperty(value = "")
  public String getNames() {
    return names;
  }

  public void setNames(String names) {
    this.names = names;
  }

  public UserRegistrationRequest organizationName(String organizationName) {
    this.organizationName = organizationName;
    return this;
  }

   /**
   * Get organizationName
   * @return organizationName
  **/
  @ApiModelProperty(value = "")
  public String getOrganizationName() {
    return organizationName;
  }

  public void setOrganizationName(String organizationName) {
    this.organizationName = organizationName;
  }

  public UserRegistrationRequest password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public UserRegistrationRequest position(String position) {
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @ApiModelProperty(value = "")
  public String getPosition() {
    return position;
  }

  public void setPosition(String position) {
    this.position = position;
  }

  public UserRegistrationRequest role(RoleEnum role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @ApiModelProperty(value = "")
  public RoleEnum getRole() {
    return role;
  }

  public void setRole(RoleEnum role) {
    this.role = role;
  }

  public UserRegistrationRequest serverName(String serverName) {
    this.serverName = serverName;
    return this;
  }

   /**
   * Get serverName
   * @return serverName
  **/
  @ApiModelProperty(value = "")
  public String getServerName() {
    return serverName;
  }

  public void setServerName(String serverName) {
    this.serverName = serverName;
  }

  public UserRegistrationRequest subscriptionPlanCode(String subscriptionPlanCode) {
    this.subscriptionPlanCode = subscriptionPlanCode;
    return this;
  }

   /**
   * Get subscriptionPlanCode
   * @return subscriptionPlanCode
  **/
  @ApiModelProperty(value = "")
  public String getSubscriptionPlanCode() {
    return subscriptionPlanCode;
  }

  public void setSubscriptionPlanCode(String subscriptionPlanCode) {
    this.subscriptionPlanCode = subscriptionPlanCode;
  }

  public UserRegistrationRequest timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Get timezone
   * @return timezone
  **/
  @ApiModelProperty(value = "")
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserRegistrationRequest userRegistrationRequest = (UserRegistrationRequest) o;
    return Objects.equals(this.allowedApplicationIds, userRegistrationRequest.allowedApplicationIds) &&
        Objects.equals(this.attributes, userRegistrationRequest.attributes) &&
        Objects.equals(this.awsCustomerId, userRegistrationRequest.awsCustomerId) &&
        Objects.equals(this.email, userRegistrationRequest.email) &&
        Objects.equals(this.expirationDate, userRegistrationRequest.expirationDate) &&
        Objects.equals(this.names, userRegistrationRequest.names) &&
        Objects.equals(this.organizationName, userRegistrationRequest.organizationName) &&
        Objects.equals(this.password, userRegistrationRequest.password) &&
        Objects.equals(this.position, userRegistrationRequest.position) &&
        Objects.equals(this.role, userRegistrationRequest.role) &&
        Objects.equals(this.serverName, userRegistrationRequest.serverName) &&
        Objects.equals(this.subscriptionPlanCode, userRegistrationRequest.subscriptionPlanCode) &&
        Objects.equals(this.timezone, userRegistrationRequest.timezone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowedApplicationIds, attributes, awsCustomerId, email, expirationDate, names, organizationName, password, position, role, serverName, subscriptionPlanCode, timezone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserRegistrationRequest {\n");
    
    sb.append("    allowedApplicationIds: ").append(toIndentedString(allowedApplicationIds)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    awsCustomerId: ").append(toIndentedString(awsCustomerId)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    names: ").append(toIndentedString(names)).append("\n");
    sb.append("    organizationName: ").append(toIndentedString(organizationName)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    serverName: ").append(toIndentedString(serverName)).append("\n");
    sb.append("    subscriptionPlanCode: ").append(toIndentedString(subscriptionPlanCode)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

